# Generated by Django 3.2.7 on 2021-09-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default='23.07.2021', verbose_name='Дата публикации'),
        ),
    ]
